using System;
using System.ComponentModel.DataAnnotations;

namespace BuildExeBasic.Models.DTO
{
    public class BatchDTO
    {
        public long Id { get; set; } // optional in POST

        [Required(ErrorMessage = "SitemanagerId is required")]
        public int SitemanagerId { get; set; }

        public string BatchNo { get; set; } // generated by API

        public bool Status { get; set; } = false;

        public bool CloseState { get; set; } = false;

        public Int16 CompanyId { get; set; }
        public Int16 BranchId { get; set; }

        public string SiteManager { get; set; }
    }
}
